# Generated by Django 5.0.5 on 2024-05-12 10:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zasob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_zdarzenia', models.DateTimeField(default=datetime.datetime(2024, 5, 12, 10, 13, 14, 254972, tzinfo=datetime.timezone.utc))),
                ('opis', models.CharField(max_length=255)),
                ('typ_zdarzenia', models.CharField(choices=[('INFO', 'Informacja'), ('WARN', 'Ostrzezenie'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('zasob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdarzenia.zasob')),
            ],
            options={
                'ordering': ['data_dodania', 'typ_zdarzenia'],
            },
        ),
    ]
